'use client';

import { useState, useEffect, useRef } from 'react';
import { firestore } from '@/lib/firebase';
import { collection, query, onSnapshot, orderBy, limit } from 'firebase/firestore';
import type { DevicePythonDataPoint } from '@/types';
import { useAuth } from './use-auth';

function generateMockDataPoint(lastPoint?: DevicePythonDataPoint): DevicePythonDataPoint {
  const now = Date.now() / 1000;
  const baseHr = lastPoint?.heartRate ?? 75;
  const baseTemp = lastPoint?.temperature ?? 36.8;

  return {
    id: `mock_${now}`,
    ax: Math.random() * 2 - 1,
    ay: Math.random() * 2 - 1,
    az: Math.random() * 2 - 1,
    gx: Math.random() * 0.1,
    gy: Math.random() * 0.1,
    gz: Math.random() * 0.1,
    delta: Math.random() * 40,
    theta: Math.random() * 30,
    lowAlpha: Math.random() * 20,
    highAlpha: Math.random() * 15,
    highBeta: Math.random() * 10,
    highGamma: Math.random() * 8,
    heartRate: baseHr + (Math.random() - 0.5) * 4,
    temperature: baseTemp + (Math.random() - 0.5) * 0.2,
    timestamp: now,
  };
}

// NOTE: Hardcoding user ID for demonstration purposes to match Python script.
const DEMO_USER_ID = "25zoRah4wZsAKzLeZJpL";

export function useDeviceData(pointsLimit: number): DevicePythonDataPoint[] {
  const { user } = useAuth();
  const [data, setData] = useState<DevicePythonDataPoint[]>([]);
  const dataRef = useRef(data);
  dataRef.current = data;

  useEffect(() => {
    // If Firebase is not configured, use mock data
    if (!firestore) {
      console.warn('Firebase not configured. Using mock data stream.');
      const interval = setInterval(() => {
        const newPoint = generateMockDataPoint(dataRef.current[dataRef.current.length - 1]);
        setData(prev => [...prev, newPoint].slice(-pointsLimit));
      }, 2000);
      return () => clearInterval(interval);
    }
    
    // For this demo, we use a hardcoded user ID to ensure we show the data
    // being generated by the Python script, regardless of who is logged in.
    const effectiveUserId = DEMO_USER_ID;

    if (!effectiveUserId) {
        setData([]);
        return;
    }

    const dataCollectionRef = collection(firestore, 'users', effectiveUserId, 'realtime_data');
    const q = query(dataCollectionRef, orderBy('ts', 'desc'), limit(pointsLimit));

    const unsubscribe = onSnapshot(q, (querySnapshot) => {
        const points: DevicePythonDataPoint[] = [];
        querySnapshot.forEach((doc) => {
            const docData = doc.data();
            points.push({
                id: doc.id,
                ax: docData.ax ?? 0,
                ay: docData.ay ?? 0,
                az: docData.az ?? 0,
                gx: docData.gx ?? 0,
                gy: docData.gy ?? 0,
                gz: docData.gz ?? 0,
                delta: docData.delta,
                theta: docData.theta,
                lowAlpha: docData.lowAlpha,
                highAlpha: docData.highAlpha,
                highBeta: docData.highBeta,
                highGamma: docData.highGamma,
                heartRate: docData.heartRate,
                temperature: docData.temperature ?? 36.8, // Add mock temp if not present
                timestamp: docData.ts, // Map `ts` from firestore to `timestamp`
            });
        });
        // Reverse to have oldest first for charts
        setData(points.reverse());
    }, (error) => {
        console.error("Error fetching device data from Firestore:", error);
    });

    return () => {
      unsubscribe();
    };
  }, [pointsLimit]);

  return data;
}
