'use client';

import { useState, useEffect } from 'react';
import { doc, onSnapshot } from 'firebase/firestore';
import { firestore } from '@/lib/firebase';
import { useAuth } from './use-auth';

export interface UserProfile {
    name: string;
    email: string;
    age: number;
    height_cm: number;
    weight_kg: number;
    job: string;
}

const USER_COLLECTION = 'users';

// NOTE: Hardcoding user ID for demonstration purposes to match Python script.
const DEMO_USER_ID = "25zoRah4wZsAKzLeZJpL";

export function useUserProfile() {
  const { user } = useAuth();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!firestore) {
      console.warn('Firestore not available, skipping profile listener.');
      setLoading(false);
      return;
    }
    
    // For this demo, we use a hardcoded user ID to ensure we show the data
    // being generated by the Python script, regardless of who is logged in.
    const effectiveUserId = DEMO_USER_ID;

    if (!effectiveUserId) {
        setLoading(false);
        setProfile(null);
        return;
    }

    // The user document itself contains the profile info.
    const docRef = doc(firestore, USER_COLLECTION, effectiveUserId);
    
    const unsubscribe = onSnapshot(docRef, (docSnap) => {
      if (docSnap.exists()) {
        const data = docSnap.data();
        setProfile({
          name: data.name || 'N/A',
          email: user?.email || data.email || 'N/A', // Prefer logged-in user email
          age: data.age || 0,
          height_cm: data.height_cm || 0,
          weight_kg: data.weight_kg || 0,
          job: data.job || 'N/A'
        });
      } else {
        console.log("No such document at path:", docRef.path);
        setProfile(null);
      }
      setLoading(false);
    }, (error) => {
      console.error("Error fetching user profile:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [user]);

  return { profile, loading };
}
